name: update

on:
  push:
    branches: 
      - main
  workflow_dispatch:
  schedule:
    # Daily at 16:00 JST (07:00 UTC)
    - cron: '*/5 * * * *'

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Pull latest changes
        run: git pull
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install necessary Python packages
        run: pip install pandas geopandas requests

      - name: Run Python
        run: python ./code/lightning_collect.py

      - name: Commit and push if content changed
        env:
          GITHUB_TOKEN: ${{ secrets.PAT2 }}
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push https://x-access-token:${{ secrets.PAT2 }}@github.com/${{ github.repository }} HEAD:main